<?php

namespace AppBundle\Repository;

/**
 * ApmokejimaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ApmokejimaiRepository extends \Doctrine\ORM\EntityRepository
{
}
