<?php

namespace AppBundle\Repository;

/**
 * AtaskaitosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AtaskaitosRepository extends \Doctrine\ORM\EntityRepository
{
}
