<?php

namespace AppBundle\Repository;

/**
 * ataskaitos_tipaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ataskaitos_tipasRepository extends \Doctrine\ORM\EntityRepository
{
}
