<?php

namespace AppBundle\Repository;

/**
 * Atsargine_kopijaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Atsargine_kopijaRepository extends \Doctrine\ORM\EntityRepository
{
}
