<?php

namespace AppBundle\Repository;

/**
 * Atsargines_kopijosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Atsargines_kopijosRepository extends \Doctrine\ORM\EntityRepository
{
}
