<?php

namespace AppBundle\Repository;

/**
 * DarbaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DarbaiRepository extends \Doctrine\ORM\EntityRepository
{
}
