<?php

namespace AppBundle\Repository;

/**
 * MiestasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MiestasRepository extends \Doctrine\ORM\EntityRepository
{
}
