<?php

namespace AppBundle\Repository;

/**
 * perdavimo_tipaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class perdavimo_tipasRepository extends \Doctrine\ORM\EntityRepository
{
}
