<?php

namespace AppBundle\Repository;

/**
 * PranesimaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PranesimasRepository extends \Doctrine\ORM\EntityRepository
{
}
