<?php

namespace AppBundle\Repository;

/**
 * pran_vartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class pran_vartRepository extends \Doctrine\ORM\EntityRepository
{
}
