<?php

namespace AppBundle\Repository;

/**
 * SiuntiniaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SiuntiniaiRepository extends \Doctrine\ORM\EntityRepository
{
}
