<?php

namespace AppBundle\Repository;

/**
 * UzsakymaiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UzsakymasRepository extends \Doctrine\ORM\EntityRepository
{
}
