<?php

namespace AppBundle\Repository;

/**
 * uzsakymo_busenosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class uzsakymo_busenaRepository extends \Doctrine\ORM\EntityRepository
{
}
