<?php

namespace AppBundle\Repository;

/**
 * vart_roleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vart_roleRepository extends \Doctrine\ORM\EntityRepository
{
}
